services:
  common-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    environment:
      - ServiceUrls__DairyService=http://host.docker.internal:8088
      - ServiceUrls__GroceryService=http://host.docker.internal:8089
      - ServiceUrls__StationaryService=http://host.docker.internal:8090
    extra_hosts:
      - "host.docker.internal:host-gateway"

  common-frontend:
    build:
      context: ./Common.Frontend
      dockerfile: Dockerfile
    ports:
      - "4203:80"
    depends_on:
      - common-api

