services:
  common-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    environment:
      - ServiceUrls__DairyService=http://host.docker.internal:8088
      - ServiceUrls__GroceryService=http://host.docker.internal:8089
      - ServiceUrls__StationaryService=http://host.docker.internal:8090
    extra_hosts:
      - "host.docker.internal:host-gateway"
